### ISSUE TITLE
ルーティング不足？

### ISSUE THREAD

**Issue by y-hasegawa-froide** [ogihara-ryo/ogihara-ryo#1]
ブログ登録時に

undefined method `blog_category_path' for #<#<Class:0x007f804bc79228>:0x007f8052832780>
Did you mean?  blog_category_link

のエラーが発生。
routesの不足っぽい

**Comment by ogihara-ryo** [comment]
まさか clone する人が現れるとは思いませんでした。
ブログカテゴリーの概念は消そうとしている最中でした。。

**Comment by ogihara-ryo** [comment]
https://github.com/ogihara-ryo/ogihara-ryo/commit/3c22efabe9c91532c735831f06441d17a434c967
